### ISSUE TITLE
It seems missing some file in repositories

### ISSUE THREAD

**Issue by leofcshen** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#10]
I got error while open `Launch_AutoGUI.ahk` with the `d4209fb4118da462296e36c2c06679c01b5f100d` version

`Error: Failed attempt to launch program or document:
Action: <D:\Test\Easy-Auto-GUI-for-AHK-v2\required\\AutoHotKey Exe\AutoHotkeyV1.exe>
Params: <"D:\Test\Easy-Auto-GUI-for-AHK-v2\required\\AutoGUI.ahk">
`

After copy `/required/AutoHotKey Exe` folder from old version, open `Launch_AutoGUI.ahk` run success

**Comment by samfisherirl** [comment]
> I got error while open `Launch_AutoGUI.ahk` with the `d4209fb4118da462296e36c2c06679c01b5f100d` version
> 
> `Error: Failed attempt to launch program or document: Action: <D:\Test\Easy-Auto-GUI-for-AHK-v2\required\\AutoHotKey Exe\AutoHotkeyV1.exe> Params: <"D:\Test\Easy-Auto-GUI-for-AHK-v2\required\\AutoGUI.ahk"> `
> 
> After copy `/required/AutoHotKey Exe` folder from old version, open `Launch_AutoGUI.ahk` run success

If you check the release, it includes exe's from autohotkeyv1.exe that is required to run. 

I didn't see it in the original main branch, and shouldn't be included in the repository code- only in the release. 

I'm glad you called this  out, I'll put in a test on launch for the script to look for the exe's. If not present, a notification stating the user should download the release.
