### ISSUE TITLE
Script File Not Found

### ISSUE THREAD

**Issue by rickf2** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#11]
1. Every time I attempt to execute this, I end up with a file not found error, and it's trying to point to C: \ program and that's it. It's like it doesn't recognize the space in PROGRAM FILES. This is the second time I've installed it, the first time I cloned it. And the same thing happened to where I cloned it at which was a path that also had a space in it. 

2. Also, when I saved the file, it. will not save. It shows that it's there, but I cannot retrieve it.

Thank you,
Rick F

**Comment by samfisherirl** [comment]
> 1. Every time I attempt to execute this, I end up with a file not found error, and it's trying to point to C: \ program and that's it. It's like it doesn't recognize the space in PROGRAM FILES. This is the second time I've installed it, the first time I cloned it. And the same thing happened to where I cloned it at which was a path that also had a space in it.
> 2. Also, when I saved the file, it. will not save. It shows that it's there, but I cannot retrieve it.
> 
> Thank you, Rick F

Which version do you have downloaded, do you have the latest downloaded from the release page?

**Comment by rickf2** [comment]
i do,  i opened this issue within an hour after I downloaded it
Ver 2.5.8 Is what i have

**Comment by rickf2** [comment]
![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/139743727/95e99c79-cf06-4b5a-bf28-ddce3b387a36)

**Comment by rickf2** [comment]
![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/139743727/c86b2934-7bff-4545-980a-2fd011d60b71)

**Comment by samfisherirl** [comment]
> ![image](https://user-images.githubusercontent.com/139743727/283969540-c86b2934-7bff-4545-980a-2fd011d60b71.png)

2.5.8 is version of the easy_autogui original  program which is not mine. this code is a mod to wrap the original on autohotkeyv2. 

https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/releases/download/v1.6.5.5/Easy-Auto-GUI-v1.6.5-for-AHK-v2.2.zip

try downloading v2, and ensure you have v2 autohotkey installed

**Comment by rickf2** [comment]
yes, i ha e been usinf v2 for a while now

Thank you, I will try your link and let you know

**Comment by rickf2** [comment]
OMG, Thank you so much!!!!   very nice!
