### ISSUE TITLE
Opening a GUI that i have started

### ISSUE THREAD

**Issue by rickf2** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#12]
The scroll window for the activate and clone is not working properly. The scroll bars do not work, and I'm not sure which window to activate. Maybe it's a training issue on my part, but I don't think it's working. It's not that easy or user friendly. Here is what I'm getting when. I hit the clone button. Also, the scroll bar is not working at all, so I cannot get to the bottom, which I believe is what I'm supposed to be activating. Anyway, could you look into it, please?

![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/139743727/cd356258-64cb-4bbf-8347-fc1d3cdb7ddf)

**Comment by samfisherirl** [comment]
> The scroll window for the activate and clone is not working properly. The scroll bars do not work, and I'm not sure which window to activate. Maybe it's a training issue on my part, but I don't think it's working. It's not that easy or user friendly. Here is what I'm getting when. I hit the clone button. Also, the scroll bar is not working at all, so I cannot get to the bottom, which I believe is what I'm supposed to be activating. Anyway, could you look into it, please?
> 
> ![image](https://user-images.githubusercontent.com/139743727/284378750-cd356258-64cb-4bbf-8347-fc1d3cdb7ddf.png)

this is a part of the  original program. I don't believe scripts could be modified after closing. 

either way, the best method is...save the script, then if you want to modify the GUI, clone the window.
