### ISSUE TITLE
Opening Files not working

### ISSUE THREAD

**Issue by C9Bad** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#13]
When I open a file. The Show/Hide preview doesn't work. It just shows the normal blank preset GUI. It correctly shows it when I execute but not on with Show/Hide..
I have to use the Window Cloning Tool in order to get it to work.

**Comment by samfisherirl** [comment]
> When I open a file. The Show/Hide preview doesn't work. It just shows the normal blank preset GUI. It correctly shows it when I execute but not on with Show/Hide.. I have to use the Window Cloning Tool in order to get it to work.

saving for later, opening existing scripts, neither were functional in the original script. 

if youre able to create a blank gui and add to it, or clone windows, then its not dysfunctional. let me know if this is the case.

**Comment by C9Bad** [comment]
yes it is still usable although it feels unconventional and is a major flaw in my opinion.

**Comment by samfisherirl** [comment]
> yes it is still usable although it feels unconventional and is a major flaw in my opinion.

noted
