### ISSUE TITLE
Windows Cloning Tool doubles the size

### ISSUE THREAD

**Issue by Cyberklabauter** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#14]
When I use the Windows Clone Tool to clone my AHK 1 window, it doubles in size. The preview looks perfect in size, but when I run the code, the window appears much larger. 

My OS is Win11 and my screen resolution is 1920 x 1080.

Thank you for your excellent tool. It is really good and helpfull!

**Comment by samfisherirl** [comment]
myGui.Opt('-DPIScale")

**Comment by Cyberklabauter** [comment]
When I use myGui.Opt('-DPIScale') for my captured GUI, it is displayed at the correct size. 
The problem probably occurs because my display settings are scaled to 150%. If I set it to 100%, the size of the window and its elements are captured correctly. 

I don't know if it is possible to switch to 100% during the capture process and then back to the original screen scaling.

Anyways: I can work with it perfectly know. Thank you!

**Comment by samfisherirl** [comment]
> When I use myGui.Opt('-DPIScale') for my captured GUI, it is displayed at the correct size. The problem probably occurs because my display settings are scaled to 150%. If I set it to 100%, the size of the window and its elements are captured correctly.
> 
> I don't know if it is possible to switch to 100% during the capture process and then back to the original screen scaling.
> 
> Anyways: I can work with it perfectly know. Thank you!

I would recommend using my GuiResizer addons, and GuiResizer. 

https://www.autohotkey.com/boards/viewtopic.php?f=83&t=113921

https://github.com/samfisherirl/GuiResizer-Addons

Provides scaling capabilities to Gui Controls

**Comment by Cyberklabauter** [comment]
Wow, what a amazing project. Thank you for the hint!!!
