### ISSUE TITLE
Toolbars aren't built properly

### ISSUE THREAD

**Issue by Banaanae** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#17]
Toolbars are not built properly
It makes a line `hToolbar := CreateToolbar()` but never defines `CreateToolbar()`

To reproduce
1) Run script
2) Add ToolBar via Design Mode
3) Execute script, you will get
![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/83927639/a442bceb-87a2-40d7-a76e-c0f175328c64)

The help button on properties also does nothing.
![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/83927639/2dfc0e93-8e58-4ad7-8ef0-de7a96d9e212)

<sub>Unrelated, how does this script actually run? I found the v1->v2 converter in this repo, does it convert the outputted script? Or the base script? Or some other way</sub>

**Comment by samfisherirl** [comment]
> Toolbars are not built properly It makes a line `hToolbar := CreateToolbar()` but never defines `CreateToolbar()`
> 
> To reproduce
> 
> 1. Run script
> 2. Add ToolBar via Design Mode
> 3. Execute script, you will get
>    ![image](https://private-user-images.githubusercontent.com/83927639/312060654-a442bceb-87a2-40d7-a76e-c0f175328c64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU3MTUsIm5iZiI6MTcxMDI5NTQxNSwicGF0aCI6Ii84MzkyNzYzOS8zMTIwNjA2NTQtYTQ0MmJjZWItODdhMi00MGQ3LWE3NmUtYzBmMTc1MzI4YzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZDMzODFiNWNjMGNiYWFiZWIwMmMyMGI0MWZlODhjNDJlZDlkNWRmMjgwNDQyMjE4YmNmMDdjZWEyN2M3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sZfY8Id6bzWfYIsu3ehzRiotTSY0E8yGEIXOsUM2Un0)
> 
> The help button on properties also does nothing. ![image](https://private-user-images.githubusercontent.com/83927639/312061773-2dfc0e93-8e58-4ad7-8ef0-de7a96d9e212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU3MTUsIm5iZiI6MTcxMDI5NTQxNSwicGF0aCI6Ii84MzkyNzYzOS8zMTIwNjE3NzMtMmRmYzBlOTMtOGU1OC00YWQ3LThlZjAtZGU3YTk2ZDllMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwY2Y3Yjk4YjUwNmQ1NDgzMThkNGVmOWRiNmZiYmE3MzNiMWZiYTBmNDJkMTU5YjliMjAyMDg0MjgwNzhhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xNET9NbYqZAbnjprDZDpTN5E5oFDiCRIUYyXpQRmJzA)
> 
> Unrelated, how does this script actually run? I found the v1->v2 converter in this repo, does it convert the outputted script? Or the base script? Or some other way

good catch, thanks. Ill have an update in a day or two pushed. 

Its a v1 script, with v2 wrapped around the autogui app, converting every time a change is made and every time you save.
