### ISSUE TITLE
When I click Convert to Executable, there is a big red X?

### ISSUE THREAD

**Issue by AntDX316** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#18]
When I click Convert to Executable, there is a big red X?

Am I doing something wrong?

**Comment by samfisherirl** [comment]
> When I click Convert to Executable, there is a big red X?
> 
> Am I doing something wrong?

Some functionality wont work, for compiling to exe, right click on the script in windows explorer and convert to exe that way. Search for ahk2exe if you dont have it installed.
