### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DarrenLindsey** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#19]
![Screenshot 2024-06-10 133622](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/29126351/9d83be31-d5dd-4d8a-90b3-9792e53d3dbd)

Issues seems to need two ampersands "if A_LineFile = A_ScriptFullPath && !A_IsCompiled"

**Comment by samfisherirl** [comment]
it should look like this 

```
if A_LineFile = A_ScriptFullPath && !A_IsCompiled
```

**Comment by DarrenLindsey** [comment]
How would I go about changing that bit of code to be the default? If I make the changes to one script and hit execute, it just makes a new script when I add a new element.

**Comment by samfisherirl** [comment]
update to the latest version, it shouldnt output that at all

**Comment by DarrenLindsey** [comment]
Thanks for that, I must have managed to download the wrong one.
