### ISSUE TITLE
ControlColor

### ISSUE THREAD

**Issue by PavelDvorak** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#2]
hello 
great tool, works great! thanks!!

i played with the options, an error appeared on the line starting `ControlColor`: 
```
myGui := Gui()
myGui.Opt("+hWndhMainWnd")
ogchTxtOptions := myGui.Add("Text", "x8 y16 w190 h348 +0x200 +Border", "Options")
hTxtOptions := ogchTxtOptions.hwnd
ControlColor(hTxtOptions, hMainWnd, 0x76E7A6)
```
error upon execution: 
```
Warning: This variable appears to never be assigned a value.
Specifically: global ControlColor
```

**Comment by samfisherirl** [comment]
> hello great tool, works great! thanks!!
> 
> i played with the options, an error appeared on the line starting `ControlColor`:
> 
> ```
> myGui := Gui()
> myGui.Opt("+hWndhMainWnd")
> ogchTxtOptions := myGui.Add("Text", "x8 y16 w190 h348 +0x200 +Border", "Options")
> hTxtOptions := ogchTxtOptions.hwnd
> ControlColor(hTxtOptions, hMainWnd, 0x76E7A6)
> ```
> 
> error upon execution:
> 
> ```
> Warning: This variable appears to never be assigned a value.
> Specifically: global ControlColor
> ```

I'm familiar with the issue from the original application. It requires the ControlColor.ahk file, found in the "required\convert" folder.
From memory you need to Include this in your app.  

I just looked over the file, I see it needs to be converted to ahkv2 and it appears to be fairly simple. For now, use the AHKv2 method backcolor https://www.autohotkey.com/docs/v2/lib/Gui.htm#BackColor

I'll see if I want to convert or make backcolor the primary method. Thanks for the heads up. 


![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/98753696/c8fe3a33-c37b-46cc-9423-36b5cdbe82f2)

**Comment by samfisherirl** [comment]
@PavelDvorak 
can you provide the instance and steps you went through to get to this point

**Comment by PavelDvorak** [comment]
hello 

1. create a control in the preview window, for example `Text` control
https://pasteboard.co/FIGP2SkAnZMI.png
2. right click on it, choose "Properties"
3. click on tab "Font", in the box "Control color", change background color, click on Apply/OK
https://pasteboard.co/xtzHHZVzvyQX.png

A line starting with "ControlColor" is generated.
https://pasteboard.co/TXIS8qBh6Ozs.png

**Comment by samfisherirl** [comment]
> hello
> 
> 1. create a control in the preview window, for example `Text` control
>    https://pasteboard.co/FIGP2SkAnZMI.png
> 2. right click on it, choose "Properties"
> 3. click on tab "Font", in the box "Control color", change background color, click on Apply/OK
>    https://pasteboard.co/xtzHHZVzvyQX.png
> 
> A line starting with "ControlColor" is generated. https://pasteboard.co/TXIS8qBh6Ozs.png

put an update out a few hours ago fixing a lot of those issues. it actually caused a few errors, some if not all should be taken care of. download the new release and let me know if you have any issues. For now, Its just a patch to remove that function, Ill add a new one with ahkv2 classes for guicontrol color soon,.

**Comment by samfisherirl** [comment]
> hello great tool, works great! thanks!!
> 
> i played with the options, an error appeared on the line starting `ControlColor`:
> 
> ```
> myGui := Gui()
> myGui.Opt("+hWndhMainWnd")
> ogchTxtOptions := myGui.Add("Text", "x8 y16 w190 h348 +0x200 +Border", "Options")
> hTxtOptions := ogchTxtOptions.hwnd
> ControlColor(hTxtOptions, hMainWnd, 0x76E7A6)
> ```
> 
> error upon execution:
> 
> ```
> Warning: This variable appears to never be assigned a value.
> Specifically: global ControlColor
> ```

Good news,

I finally got around to fixing Control Color, its not in Easy AutoGUI yet, it will be by end of week. Nonetheless, Ive posted just the ahkv2 version of ControlColor here  https://github.com/samfisherirl/ControlColor.ahk-v2
