### ISSUE TITLE
When creating a Tray Menu it does not add the menu item, only the icon

### ISSUE THREAD

**Issue by LaserMade** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#27]
I was here to add a different Tray menu issue and when trying to recreate that issue I came across this one:

Adding a menu item to the tray menu does not always create the Tray.add(...) line to the script. When it isnt working it only adds Tray.setIcon(...) Picture attached as an example. None of the code in the picture has been modified in any way; it was all autoproduced.

The only thing I've done differently from the last time this was working is this time I created a button first.

![AutoGui Issue 27](https://github.com/user-attachments/assets/e6363fc7-4698-444a-ba01-e4f5362051be)

**Comment by samfisherirl** [comment]
> I was here to add a different Tray menu issue and when trying to recreate that issue I came across this one:
> 
> Adding a menu item to the tray menu does not always create the Tray.add(...) line to the script. When it isnt working it only adds Tray.setIcon(...) Picture attached as an example. None of the code in the picture has been modified in any way; it was all autoproduced.
> 
> The only thing I've done differently from the last time this was working is this time I created a button first.
> 
> ![AutoGui Issue 27](https://private-user-images.githubusercontent.com/162772380/359652759-e6363fc7-4698-444a-ba01-e4f5362051be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMTU0MjYsIm5iZiI6MTcyNTIxNTEyNiwicGF0aCI6Ii8xNjI3NzIzODAvMzU5NjUyNzU5LWU2MzYzZmM3LTQ2OTgtNDQ0YS1iYTAxLWU0ZjUzNjIwNTFiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQxODI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTM2YmM4NGViMGVmNzU5ZDc0N2VjMzZhZTg1MDM0ZmRmOGYwZjJjM2ZlMjE0MTJhYWE2ODUxNzk0MzUzNjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OWioSK5wfUk0vUpTLA6bvsKIHH43iGIAI1HLEOAuLak)

ill work on this
