### ISSUE TITLE
The problem of saving and reloading the project

### ISSUE THREAD

**Issue by patrio4** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#28]
When I save the project, if I close the program and open it again and load the project, the design environment does not open anymore, there are only codes, and on the toolbars, if I press the button, a new tab opens with a new window to start.
Apparently, when the program loads a saved file, it can no longer open it in the design structure
Please help me, it is very important to me
I opened the program in admin mode, I even tested the portable version, unfortunately, it is not possible to open the project in design mode several times after closing the program.
I have installed all the essentials, I have no problem, this is my only problem
The project runs but cannot be edited in design mode

**Comment by johnmolino** [comment]
Bump....same issue

**Comment by samfisherirl** [comment]
> Bump....same issue



> When I save the project, if I close the program and open it again and load the project, the design environment does not open anymore, there are only codes, and on the toolbars, if I press the button, a new tab opens with a new window to start. Apparently, when the program loads a saved file, it can no longer open it in the design structure Please help me, it is very important to me I opened the program in admin mode, I even tested the portable version, unfortunately, it is not possible to open the project in design mode several times after closing the program. I have installed all the essentials, I have no problem, this is my only problem The project runs but cannot be edited in design mode

I've updated https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/blob/main/.github/ISSUE_TEMPLATE/warning-donot-report-issues-regarding-features-or-importing-guis.md
