### ISSUE TITLE
can you add a shorcut?

### ISSUE THREAD

**Issue by kevindevm** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#3]
a shorcut to copy control like 
ctrl alt (or whatever) and mouse click and hold move an drop a copy of the elemnt?

**Comment by kevindevm** [comment]
@samfisherirl did you add a shortcut?

**Comment by samfisherirl** [comment]
> @samfisherirl did you add a shortcut?

I have not had time to dig through the documentation. At this time, I wont be adding new features to the existing solution, but, if you were to help I won't be opposed to it. I'd be looking at many hours to provide a custom shortcut for you. If you want to help get me closer, I would me more amenable. As for the issue, it isn't necessarily a program issue, there for it's been closed. 
If you were to read the documentation and find if there are existing shortcuts, what those are, I can adjust and add what you're looking for. We may find that there is an existing shortcut.
