### ISSUE TITLE
Issues manually editing a file and using script directives

### ISSUE THREAD

**Issue by marizzz95** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#30]
Including script directives in the title because it seems like all it does is prepend text to the currently open file which causes the same problem.

The Problem: 
You can't manually edit a file. If you do, it duplicates the file. The duplicate file you can freely edit but it is not connected to the GUI builder preview.
When you edit the GUI in the builder preview, it only edits the original file associated with the GUI, so you have to duplicate it again and copy all your changes again

**Comment by samfisherirl** [comment]
have an alternative editor ready.
