### ISSUE TITLE
script directives do not save

### ISSUE THREAD

**Issue by marizzz95** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#31]
Like the title says, if you change anything in the script directives, including checking custom includes, it does not save when you open it the next time.

**Comment by samfisherirl** [comment]
https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/blob/main/.github/ISSUE_TEMPLATE/warning-donot-report-issues-regarding-features-or-importing-guis.md
