### ISSUE TITLE
option to change gui's font size?

### ISSUE THREAD

**Issue by PENchanter** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#7]
Hi! This project looks very interesting!!  

The first **issue** I have is that the actual font size used in the gui... the toolbar  and side menu is unreadable without squinting with my poor eyesight. :(

Could you add an option to customize the size of the different gui elements?

**Comment by samfisherirl** [comment]
> Hi! This project looks very interesting!!
> 
> The first **issue** I have is that the actual font size used in the gui... the toolbar and side menu is unreadable without squinting with my poor eyesight. :(
> 
> Could you add an option to customize the size of the different gui elements?

I assume you are referring to the GUI for EasyAutoGUI; screenshots help. 

here's the fix:
- right click properties on exe
- 
![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/98753696/ad8a1cf9-c09b-4fc4-bff0-5a6d575f7d35)

![image](https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/assets/98753696/789874f9-2a1b-43f9-94d6-eb0eb4448774)
