### ISSUE TITLE
compile error 'ClassOrderedMap.ahk' not found?

### ISSUE THREAD

**Issue by PENchanter** [samfisherirl/Easy-Auto-GUI-for-AHK-v2#8]
Hi again... You make reference to an **_.exe_** version of "**Launch_AutoGUI.ahk**" but no such file was included within the "**Easy-Auto-GUI-for-AHK-v2-main.zip**" that is currently available for download.  

Am I expected to compile the .ahk file myself? I did try this and ran into the following error:      

### Ahk2Exe Error  
\#include file cannot be opened.  

**_Specifically_**:  
"`C:\Temp\Easy-Auto-GUI-for-AHK-v2-main\lib\ClassOrderedMap.ahk`"  

I checked for this file and found two:  

`C:\Temp\Easy-Auto-GUI-for-AHK-v2-main\required\Lib\ClassOrderedMap.ahk`  

`C:\Temp\Easy-Auto-GUI-for-AHK-v2-main\required\convert\lib\ClassOrderedMap.ahk`  

Please advise...

**Comment by samfisherirl** [comment]
https://github.com/samfisherirl/Easy-Auto-GUI-for-AHK-v2/releases/download/v1.6.2/Easy-Auto-GUI-for-AHK-v2.-.1.zip

I recommend some tutorials on github and autohotkey for foundational questions, ensuring you have a smooth dev experience,
